### ISSUE TITLE
Treat SHACL rules and test cases as first-class components of building blocks

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#10]
SHACL rules (possibly a subset?) and test cases are required to use the building block in the wild - these should be either placed in public directories or copied to build tree - and linked from Slate app as a key resource.

This may help with the inheritance of SHACL rules too.

**Comment by avillar** [comment]
I've changed the SHACL rules output so that all files (own and inherited) are shown in the documentation: https://icsm-au.github.io/3d-csdm-schema/build/generateddocs/slate-build/csdm/features/CSD/#validation

How should we handle test cases?

**Comment by rob-metalinkage** [comment]
I think standalone validation report is sufficient.
