### ISSUE TITLE
Handle remote YAML or JSON schema missing

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#16]
When a reference to a remote schema is only available as YAML or JSON the processing fails:

e.g. 

 Error resolving reference https://raw.githubusercontent.com/opengeospatial/ogcapi-records/master/core/openapi/schemas/recordGeoJSON.json from /workspace/build-local/annotated/geo/geodcat/dcat-records/schema.json

it is to be expected that normative references are only available as one of JSON/YAML in many cases..

**Comment by avillar** [comment]
This happens because of a blanket yaml -> json replacement in the schemas when generating the annotated JSON version. Need to update the code so that only references to known BB schemas are replaced. I've pushed a fixed that I think should fix this.

Where is this repo (i.e., can I test this)?

**Comment by rob-metalinkage** [comment]
Geodcat-api-records

**Comment by avillar** [comment]
Is this working now?

**Comment by avillar** [comment]
I'm closing this as it seems to be fixed, please reopen if that's not the case.
