### ISSUE TITLE
Validation Report 

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#17]
Validation reports are generated for individual cases - but for a complex suite of inter-related components with many tests this is awkward to check.

Generate a machine readable validation report and consolidate into an aggregate report, and run a CSS styling over this as per register.html

**Comment by avillar** [comment]
Examples of implemented reports:

- http://blocks.ogc.org/tests/report.html
- https://icsm-au.github.io/3d-csdm-schema/build/tests/report.html

I need to fix the links to the resources, though...

**Comment by rob-metalinkage** [comment]
Cool - is it possible to have just summaries - what rule was validated, which upstream BB defined it and result (group by BB, order by depth of parentage) - and link to detailed reports.

**Comment by rob-metalinkage** [comment]
Agree to collapse entries by default.

Also report header not correctly labelling the current BB

**Comment by avillar** [comment]
The entries are collapsed by default and can be individually opened, and the headers look right to me. I think this can be closed.
