### ISSUE TITLE
DateTime parsing throws processing error - not validation report

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#19]
When running tests process does not handle datetime parsing elegantly...

```Failed to convert Literal lexical form to value. Datatype=http://www.w3.org/2001/XMLSchema#dateTime, Converter=<function parse_datetime at 0x7f81c50f00d0>
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/isodate/isodatetime.py", line 51, in parse_datetime
    datestring, timestring = datetimestring.split('T')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by avillar** [comment]
This is a warning that rdflib outputs to the console directly. It's not an error per-se, since rdflib is [catching the exception and setting the literal to null](https://github.com/RDFLib/rdflib/blob/b0392f0a50db3b49cf6ec93bfbe0672a0fba16d6/rdflib/term.py#L2127). 

Options:

1. Disable logging warnings for rdflib.term
2. Try to capture the warning logstream and add it to the log.

**Comment by avillar** [comment]
Ok, I went ahead with option 2. I haven't managed to remove the warning from the logging output, but at least we now capture it, mark is as an error, and add it to the log.

**Comment by rob-metalinkage** [comment]
Ok that's good enough.  Is this an issue we should raise with rdflib though... it seems a clunky option assuming someone is reading a log output...

**Comment by avillar** [comment]
There's definitely some logging configuration that we could apply to avoid 
it, I'll try it tomorrow.

El 20 de octubre de 2023 0:20:01 Rob ***@***.***> escribió:
>
> Ok that's good enough. Is this an issue we should raise with rdflib 
> though... it seems a clunky option assuming someone is reading a log output...
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were assigned.Message ID: 
> ***@***.***>


-- 

Sign up for OGC News 
<https://ogc.us4.list-manage.com/subscribe?u=704e02f81107a6caab1568067&id=4e4528fd9d>

**Comment by avillar** [comment]
Ok, the warning that was still appearing was from the transforms, not the validation. I've disabled warnings in transforms, since if there's a problem, it's going to be the same as in the validations.
