### ISSUE TITLE
Link slate view to source repo

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#2]
Is it possible to include  a link to the repo in the Slate app -

**Comment by avillar** [comment]
Do you mean for submodules?

**Comment by rob-metalinkage** [comment]
No - to the repository for building blocks - otherwise there is no way to find where they are developed, how to extend, where issues are discussed etc

**Comment by avillar** [comment]
Something like this (see bottom of the page)?

* https://opengeospatial.github.io/bblocks/generateddocs/slate-build/geo/geopose/basic-ypr/#for-developers
* https://opengeospatial.github.io/bblocks/generateddocs/slate-build/unstable/sosa/features/observationCollection/#for-developers

The paths and URLs are extracted from the git metadata.
