### ISSUE TITLE
integrate tests as richer examples in the slate

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#3]
To keep Slate clean we want a simple example, but to understand potential we often need to see more complex examples.

Provide a means to view more examples from the tests directly, and access the validation reports.

**Comment by avillar** [comment]
The way to do it right now is to click on the link in the "this Building Block is valid" banner. Does that suffice?

**Comment by rob-metalinkage** [comment]
Ahh- thats what happened when I clicked on it in a demo expecting it to go to the definition of valid!

I think somewhere we ought to provide a list of the examples being tested - pull out the description elements of each test with  the individual validation status.

**Comment by rob-metalinkage** [comment]
We should use http://www.opengis.net/def/status

and Under Development
http%3A//www.opengis.net/def/status/under-development

 i will update SOSA bblocks

**Comment by avillar** [comment]
Ok, I'll merge both conditions (`if validationFailed then status = invalid else status = bblockMetadata.status`).

**Comment by avillar** [comment]
BTW, http://www.opengis.net/def/status is actually being used (it is what's provided in the `status` property in `bblock.json`, minus the prefix).
