### ISSUE TITLE
Validation message

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#36]
"This building block is NOT valid."  is a bit opaque, and "valid" has semantics in the context of registries that doesnt match here   

Can it be one of either (depending on context):

"This building block has compliation errors"

or 

"Examples or tests for this building block have validation errors"

**Comment by avillar** [comment]
I've opted for "Examples or tests for this building block have validation errors", and for removing the message altogether if validation passes.
