### ISSUE TITLE
Consistency in formats available for examples

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#4]
The Slate app doesnt always offer TTL
e.g. https://opengeospatial.github.io/bblocks/generateddocs/slate-build/unstable/sosa/examples/vectorObservationFeature/#examples

The examples should be offered in JSON, as JSON-LD by default (using a reference) and TTL.

NB We will have building blocks that are not JSON based, we should have the same elements - even if a different processing chain.

**Comment by avillar** [comment]
The Slate version shows whatever's inside `examples.yaml`, but not the uplifted/TTL versions; the rationale for this was allowing the BB developer to control what's being shown in the documentation, but naturally I could add the uplifted/TTL versions of the examples (if any).

**Comment by avillar** [comment]
Uplifted versions are now displayed by default (1bc7ceb). This can be controlled by the `doc-uplift-formats` property in `bblock.json`.
