### ISSUE TITLE
Status and Maturity

### ISSUE THREAD

**Issue by avillar** [opengeospatial/bblocks-postprocess#6]
In 69b79560 I restricted the values for the status property to the leaf nodes of http://www.opengis.net/def/status :

- retired
- superseded
- experimental
- stable
- under-development
- invalid
- reserved
- submitted

I believe that we could shorten that list even further to:

- stable (active and valid)
- under-development (valid, but not stable)
- invalid (does not pass validation)
- retired or superseded (deprecated)

Maybe "submitted" could also be there to signal "this BB is not being actively developed, but hasn't been approved yet". Also, I know @rob-metalinkage doesn't like "invalid", but I'd say in this case it fits. I'm open to suggestions.

Regarding maturity, right now the allowed values are "mature", "proposal", "stable" and "development". I'm not sure about the difference between "mature" and "stable", but I think all of them can be described using status, so maybe we can do away with maturity altogether?

CC: @rob-metalinkage @doublebyte1

**Comment by rob-metalinkage** [comment]
Hi

Lets use the "status" vocabulary - and make the Slate app actually use the Rainbow as a client (grab the definition for a hover over and link to the definition so you can see it in relation to other terms.

If we decide we need other "status" terms - then we should propose this as a change to the naming authority (which probably needs to make some decisions regarding governance of our meta-model elements in future)

(NB - use case here for default view for a vocab term showing its position in a heirarchy nicely! )

**Comment by avillar** [comment]
I've removed "maturity" and added "status" under the abstract both for Slate and for Markdown.

I've also added a Rainbow lookup for "Status" and for its value (see it working here: https://opengeospatial.github.io/bblocks/generateddocs/slate-build/geo/json-fg/feature/ ).

I've had to use a workaround (calling `/vocprez/object?uri=...` directly instead of the resource URI) since the URIs are HTTP and GH Pages is HTTPS...
