### ISSUE TITLE
Validation failure and error messages from scripts

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#7]
Validation  failed with a python error:

AttributeError: 'NoneType' object has no attribute 'read'
=== End JSON Schema ===

we should always provide some context if an exception occurs in code, and of course validation processes should never raise internal exceptions - they are confusing if one expects validation errors.

**Comment by avillar** [comment]
Fixed by 101fa60acad26102f671cff495554f8b7993085d, 0a591486a6faf8917c0257efce0ed8f314050bb2 and a8b5332cc4ad3cc3956ec0fd9a431c41a98cdd62
