### ISSUE TITLE
Validation passes on fail if misconfiguration

### ISSUE THREAD

**Issue by rob-metalinkage** [opengeospatial/bblocks-postprocess#8]
** Validation error **
[Errno 2] No such file or directory: '/ogc/features/topo-feature/tests/geometry-coordinates.shacl'
=== End SHACL ===

still shows a "fail passed" - configuration errors should be a genuine failure.

**Comment by rob-metalinkage** [comment]
Also happens with syntax error in SHACL

**Comment by avillar** [comment]
So you're saying that we should raise an exception instead of just reporting it as a validation failure, right?

**Comment by rob-metalinkage** [comment]
Problem is config failures buried in individual tests is nasty.  Fails can look like they passed.  A Consolidated report will fix this if error is propagated.

**Comment by avillar** [comment]
Ok, I'll build the consolidated report, and then we'll decide whether that's enough.
